CREATE TABLE BIDS (BID_ID NUMBER(19) NOT NULL, 
BID_PRICE NUMBER(19,4) NULL, 
BID_STATUS VARCHAR2(255) NULL, 
BID_DATE DATE NULL, 
BID_ITEM_ID NUMBER(19) NULL, 
BID_BIDDER VARCHAR2(255) NULL, 
PRIMARY KEY (BID_ID))
/
